### ISSUE TITLE
Python3 Compatiblity

### ISSUE THREAD

**Issue by mclaughlinconnor** [inclement/p4a-pygame-bootstrap-components#1]
As far as I can tell, this doesn't work with Python3. I am trying to build a Python3 Pygame game with P4A and it's erroring as below.
```
[INFO]:    Will compile for the following archs: armeabi
[INFO]:    Found Android API target in $ANDROIDAPI
[INFO]:    Available Android APIs are (19, 22, 27)
[INFO]:    Requested API target 19 is available, continuing.
[INFO]:    Found NDK dir in $ANDROIDNDK
[INFO]:    Got NDK version from $ANDROIDNDKVER
[INFO]:    Using Crystax NDK 10.3.2
[INFO]:    Found virtualenv at /usr/local/bin/virtualenv
[INFO]:    ccache is missing, the build will not be optimized in the future.
[INFO]:    Found the following toolchain versions: ['4.9', '5', 'clang3.6', 'clang3.7']
[INFO]:    Picking the latest gcc toolchain, here 5
[INFO]:    No existing dists meet the given requirements!
[INFO]:    No dist exists that meets your requirements, so one will be built.
[INFO]:    Found a single valid recipe set: ['hostpython3crystax', 'pygame_bootstrap_components', u'python3crystax', 'sdl', u'pygame']
[INFO]:    The selected bootstrap is pygame
[INFO]:    # Creating dist with pygame bootstrap
[INFO]:    Dist will have name unnamed_dist_6 and recipes (python3crystax, pygame, sdl)
[INFO]:    Dist will also contain modules () installed from pip
[INFO]:    -> running cp -r /usr/local/lib/python2.7/dist-packages/pythonforandroid/bootstraps/pygame/build /home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame
[INFO]:    -> directory context /home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame
[INFO]:    <- directory context /home/connor/Python/Gran Theft Crop Toe Kivy
[INFO]:    Recipe build order is ['hostpython3crystax', 'pygame_bootstrap_components', u'python3crystax', 'sdl', u'pygame']
[INFO]:    # Downloading recipes 
[INFO]:    Downloading hostpython3crystax
[INFO]:    Skipping hostpython3crystax download as no URL is set
[INFO]:    Downloading pygame_bootstrap_components
[INFO]:    -> running mkdir -p /home/connor/.local/share/python-for-android/packages/pygame_bootstrap_components
[INFO]:    -> directory context /home/connor/.local/share/python-for-android/packages/pygame_bootstrap_components
[INFO]:    -> running basename https://github.com/kivy/p4a-pygame-bootstrap-components/archive/master.zip
[INFO]:    pygame_bootstrap_components download already cached, skipping                                                                                                                       
[INFO]:    <- directory context /home/connor/Python/Gran Theft Crop Toe Kivy
[INFO]:    Downloading python3crystax
[INFO]:    -> running mkdir -p /home/connor/.local/share/python-for-android/packages/python3crystax
[INFO]:    -> directory context /home/connor/.local/share/python-for-android/packages/python3crystax
[INFO]:    -> running basename 
[INFO]:    -> running rm -f .mark-
[INFO]:    -> running touch .mark-
[INFO]:    <- directory context /home/connor/Python/Gran Theft Crop Toe Kivy
[INFO]:    Downloading sdl
[INFO]:    Skipping sdl download as no URL is set
[INFO]:    Downloading pygame
[INFO]:    -> running mkdir -p /home/connor/.local/share/python-for-android/packages/pygame
[INFO]:    -> directory context /home/connor/.local/share/python-for-android/packages/pygame
[INFO]:    -> running basename http://pygame.org/ftp/pygame-1.9.1release.tar.gz
[INFO]:    pygame download already cached, skipping                                                                                                                                            
[INFO]:    <- directory context /home/connor/Python/Gran Theft Crop Toe Kivy
[INFO]:    # Building all recipes for arch armeabi
[INFO]:    # Unpacking recipes
[INFO]:    Unpacking hostpython3crystax for armeabi
[INFO]:    Skipping hostpython3crystax unpack as no URL is set
[INFO]:    Unpacking pygame_bootstrap_components for armeabi
[INFO]:    -> running basename https://github.com/kivy/p4a-pygame-bootstrap-components/archive/master.zip
[INFO]:    -> directory context /home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/jni                                                                                 
[INFO]:    pygame_bootstrap_components is already unpacked, skipping
[INFO]:    <- directory context /home/connor/Python/Gran Theft Crop Toe Kivy
[INFO]:    Unpacking python3crystax for armeabi
[INFO]:    -> running basename 
[INFO]:    -> directory context /home/connor/.local/share/python-for-android/build/other_builds/python3crystax-version3.5/armeabi
[INFO]:    python3crystax is already unpacked, skipping
[INFO]:    <- directory context /home/connor/Python/Gran Theft Crop Toe Kivy
[INFO]:    Unpacking sdl for armeabi
[INFO]:    Skipping sdl unpack as no URL is set
[INFO]:    Unpacking pygame for armeabi
[INFO]:    -> running basename http://pygame.org/ftp/pygame-1.9.1release.tar.gz
[INFO]:    -> directory context /home/connor/.local/share/python-for-android/build/other_builds/pygame/armeabi                                                                                 
[INFO]:    pygame is already unpacked, skipping
[INFO]:    <- directory context /home/connor/Python/Gran Theft Crop Toe Kivy
[INFO]:    # Prebuilding recipes
[INFO]:    Prebuilding hostpython3crystax for armeabi
[INFO]:    hostpython3crystax has no prebuild_armeabi, skipping
[INFO]:    Prebuilding pygame_bootstrap_components for armeabi
[INFO]:    Unpacking pygame bootstrap JNI dir components
[INFO]:    -> directory context /home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/jni
[INFO]:    sdl dir exists, so it looks like the JNI componentsare already unpacked. Skipping.
[INFO]:    <- directory context /home/connor/Python/Gran Theft Crop Toe Kivy
[INFO]:    Prebuilding python3crystax for armeabi
[INFO]:    python3crystax has no prebuild_armeabi, skipping
[INFO]:    Prebuilding sdl for armeabi
[INFO]:    sdl has no prebuild_armeabi, skipping
[INFO]:    Prebuilding pygame for armeabi
[INFO]:    Applying patches for pygame[armeabi]
[INFO]:    pygame already patched, skipping
[INFO]:    # Building recipes
[INFO]:    Building hostpython3crystax for armeabi
[INFO]:    Building pygame_bootstrap_components for armeabi
[INFO]:    Building python3crystax for armeabi
[INFO]:    Building sdl for armeabi
[INFO]:    -> directory context /home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/jni
[INFO]:    -> running ndk-build V=1
           working: make: *** [/home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/obj/local/armeabi/objs/application/src//start.o] Error 1                             Exception in thread background thread for pid 18358:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/connor/.local/lib/python2.7/site-packages/sh.py", line 2170, in background_thread
    handle_exit_code(exit_code)
  File "/home/connor/.local/lib/python2.7/site-packages/sh.py", line 1929, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/home/connor/.local/lib/python2.7/site-packages/sh.py", line 672, in handle_command_exit_code
    raise exc
ErrorReturnCode_2: 

  RAN: /home/connor/.android/crystaX/ndk-build V=1

  STDOUT:
Android NDK: WARNING:/home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/jni/../jni/application/Android.mk:application: non-system libraries in linker flags: -lpython3.5    
Android NDK:     This is likely to result in incorrect builds. Try using LOCAL_STATIC_LIBRARIES    
Android NDK:     or LOCAL_SHARED_LIBRARIES instead to list the library dependencies of the    
Android NDK:     current module    
Android NDK: WARNING:/home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/jni/../jni/png/Android.mk:png: LOCAL_LDLIBS is always ignored for static libraries    
rm -f /home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/libs/arm64-v8a/lib*.so /home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/libs/armeabi/lib*.so /home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/libs/armeabi-v7a/lib*.so /home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/libs/armeabi-v7a-hard/lib*.so /home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/libs/mips/lib*.so /home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/libs/mips64/lib*.so /home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/libs/x86/lib*.so /home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/libs/x86_64/lib*.so
rm -f /home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/libs/arm64-v8a/gdbserver /home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/libs/armeabi/gdbserver /home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/libs/armeabi-v7a/gdbserver /home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/libs/armeabi-v7a-hard/gdbserver /home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/libs/mips/gdbserver /home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/libs/mips64/gdbserver /home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/libs/x86/gdbserver /home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/libs/x86_64/gdbserver
rm -f /home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/libs/arm64-v8a/gdb.setup /home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/libs/armeabi/gdb.setup /home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/libs/armeabi-v7a/gdb.setup /home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/libs/armeabi-v7a-hard/gdb.setup /home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/libs/mips/gdb.setup /home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/libs/mips64/gdb.setup /home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/libs/x86/gdb.setup /home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/libs/x86_64/gdb.setup
[armeabi] Compile thumb  : application <= start.c
/home/connor/.android/crystaX/toolchains/arm-linux-androideabi-5/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc -MMD -MP -MF /home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/obj/local/armeabi/objs/application/src//start.o.d -fpic -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv5te -mtune=xscale -msoft-float -mthumb -Os -g -DNDEBUG -fomit-frame-pointer -fno-strict-aliasing -finline-limit=64 -I/home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/jni/../jni/application -DANDROID -I/home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/jni/../jni/application/src/ -I/home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/jni/../jni/application/../sdl/include -I/home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/jni/../jni/application/../sdl_mixer -I/home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/jni/../jni/application/../sdl_image -I/home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/jni/../jni/application/../sdl_ttf -I/home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/jni/../jni/application/../sdl_net -I/home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/jni/../jni/application/../sdl_blitpool -I/home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/jni/../jni/application/../sdl_gfx -I/home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/jni/../jni/application/../png -I/home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/jni/../jni/application/../jpeg -I/home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/jni/../jni/application/../intl -I/home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/jni/../jni/application/.. -I/home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/jni/../jni/application/../../../../other_builds/python2/armeabi/python2/python-install/include/python2.7 -finline-functions -O2 -DSDL_JAVA_PACKAGE_PATH=org_renpy_android -Wa,--noexecstack -Wformat -Werror=format-security -c -I/home/connor/.android/crystaX/sources/crystax/include -I/home/connor/.android/crystaX/platforms/android-14/arch-arm/usr/include /home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/jni/../jni/application/src//start.c -o /home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/obj/local/armeabi/objs/application/src//start.o 
/home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/jni/../jni/application/src//start.c:2:20: fatal error: Python.h: No such file or directory
compilation terminated.
/home/connor/.android/crystaX/build/core/build-binary.mk:496: recipe for target '/home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/obj/local/armeabi/objs/application/src//start.o' failed
make: *** [/home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/obj/local/armeabi/objs/application/src//start.o] Error 1


  STDERR:


[INFO]:    STDOUT:                                                                                                                                                                             
        Android NDK: WARNING:/home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/jni/../jni/application/Android.mk:application: non-system libraries in linker flags: -lpython3.5                                                                                                                                                                                        
Android NDK:     This is likely to result in incorrect builds. Try using LOCAL_STATIC_LIBRARIES    
Android NDK:     or LOCAL_SHARED_LIBRARIES instead to list the library dependencies of the    
Android NDK:     current module    
Android NDK: WARNING:/home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/jni/../jni/png/Android.mk:png: LOCAL_LDLIBS is always ignored for static libraries    
rm -f /home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/libs/arm64-v8a/lib*.so /home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/libs/armeabi/lib*.so /home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/libs/armeabi-v7a/lib*.so /home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/libs/armeabi-v7a-hard/lib*.so /home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/libs/mips/lib*.so /home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/libs/mips64/lib*.so /home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/libs/x86/lib*.so /home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/libs/x86_64/lib*.so
rm -f /home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/libs/arm64-v8a/gdbserver /home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/libs/armeabi/gdbserver /home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/libs/armeabi-v7a/gdbserver /home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/libs/armeabi-v7a-hard/gdbserver /home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/libs/mips/gdbserver /home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/libs/mips64/gdbserver /home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/libs/x86/gdbserver /home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/libs/x86_64/gdbserver
rm -f /home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/libs/arm64-v8a/gdb.setup /home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/libs/armeabi/gdb.setup /home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/libs/armeabi-v7a/gdb.setup /home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/libs/armeabi-v7a-hard/gdb.setup /home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/libs/mips/gdb.setup /home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/libs/mips64/gdb.setup /home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/libs/x86/gdb.setup /home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/libs/x86_64/gdb.setup
[armeabi] Compile thumb  : application <= start.c
/home/connor/.android/crystaX/toolchains/arm-linux-androideabi-5/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc -MMD -MP -MF /home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/obj/local/armeabi/objs/application/src//start.o.d -fpic -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv5te -mtune=xscale -msoft-float -mthumb -Os -g -DNDEBUG -fomit-frame-pointer -fno-strict-aliasing -finline-limit=64 -I/home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/jni/../jni/application -DANDROID -I/home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/jni/../jni/application/src/ -I/home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/jni/../jni/application/../sdl/include -I/home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/jni/../jni/application/../sdl_mixer -I/home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/jni/../jni/application/../sdl_image -I/home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/jni/../jni/application/../sdl_ttf -I/home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/jni/../jni/application/../sdl_net -I/home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/jni/../jni/application/../sdl_blitpool -I/home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/jni/../jni/application/../sdl_gfx -I/home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/jni/../jni/application/../png -I/home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/jni/../jni/application/../jpeg -I/home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/jni/../jni/application/../intl -I/home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/jni/../jni/application/.. -I/home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/jni/../jni/application/../../../../other_builds/python2/armeabi/python2/python-install/include/python2.7 -finline-functions -O2 -DSDL_JAVA_PACKAGE_PATH=org_renpy_android -Wa,--noexecstack -Wformat -Werror=format-security -c -I/home/connor/.android/crystaX/sources/crystax/include -I/home/connor/.android/crystaX/platforms/android-14/arch-arm/usr/include /home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/jni/../jni/application/src//start.c -o /home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/obj/local/armeabi/objs/application/src//start.o 
/home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/jni/../jni/application/src//start.c:2:20: fatal error: Python.h: No such file or directory
compilation terminated.
/home/connor/.android/crystaX/build/core/build-binary.mk:496: recipe for target '/home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/obj/local/armeabi/objs/application/src//start.o' failed
make: *** [/home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/obj/local/armeabi/objs/application/src//start.o] Error 1
[INFO]:    STDERR:

[INFO]:    COMMAND:
cd /home/connor/.local/share/python-for-android/build/bootstrap_builds/pygame/jni && /home/connor/.android/crystaX/ndk-build V=1
```
_[ For easier reading: https://pastebin.com/fPDCR5L3 ]_

I think this issue comes from `python-for-android/build/bootstrap_builds/pygame/jni/application/Android.mk` which links to a python2.7 lib (`-lpython2.7`)

Pygame did not originally work with Py3, I had to remove conflicts from the SDL and Pygame recipes to make them work with `python3crytax`

My code builds fine on Py2.7, but some core functionality is completely broken. I don't want to backport to a mostly dead version.

Any help is appreciated. Thanks.

**Comment by inclement** [comment]
Our pygame bootstrap does not support python3, and might not even really support pygame (it was only ever developed as a Kivy backend). The pygame bootstrap is also no longer supported by us, I don't expect it to ever work with python3 unless somebody external contributes the necesary changes.

python-for-android shouldn't actually allow the build to get this far, as pygame should pull in conflicting dependencies. Would you be able to open a python-for-android issue about that, including the information above and the output of `p4a recipes`?

**Comment by mclaughlinconnor** [comment]
I don't think this is an issue, I had to do some gigery-pokery in the recipes to get it to even start without complaining.
